name: Checkout and List Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      # Репозиторийді жүктеу
      - name: Checkout repository
        uses: actions/checkout@v3

      # Файлдардың тізімін шығару
      - name: Show repository files
        run: ls -la
